import library

In [ ]:
#import library
#Syntex for import
import pandas as pd

load dataset

In [ ]:
data=pd.read_excel("/content/drive/MyDrive/Colab Notebooks/airline project.xlsx")

understanding dataset

In [ ]:
Data.shape

(24, 9)

In [ ]:
Data.head(10)

,No.,Student Name,Project Title,Dataset Sheet,Rows,Columns,Status,Unnamed: 7,Data Quality Note
0,1,Aba Muxudiin Ahmed,Student Enrollment Data Analysis Using Excel,01_Enrollment,300,7,Ready,NaN,Each project dataset now includes 15 additiona...
1,2,Abdikarim Ismail Ali,Customer Purchase & Sales Performance Analysis...,02_Sales,300,7,Ready,NaN,NaN
2,3,Abdinajib Abdullahi Muse,Employee Attendance Data Analysis Using Excel,03_Emp_Attendance,300,7,Ready,NaN,NaN
3,4,Aisha Mohamed Abdullahi,Restaurant Sales and Customer Analysis Using E...,04_Restaurant,300,7,Ready,NaN,NaN
4,5,Aniso Ahmed Mohamud,TITLE NOT PROVIDED,NaN,0,0,Project title needed,NaN,NaN
5,6,Axmed Abduqadir Iman,Electricity Consumption Data Analysis Using Excel,06_Electricity,300,7,Ready,NaN,NaN
6,7,Ayuub Abdullahi Isxaakh,Hospital Patient Data Analysis Using Excel,07_Hospital,300,7,Ready,NaN,NaN
7,8,Cayni Abuukar Maxamuud,Real Estate Property Data Analysis Using Excel,08_Real_Estate,300,7,Ready,NaN,NaN
8,9,Deqo Abdulkhadir Hussein,Student Attendance and Academic Analysis,09_Academic,300,7,Ready,NaN,NaN
9,10,Faadumo Mahamed Yusuf,Internet Usage Data Analysis,10_Internet,300,7,Ready,NaN,NaN

In [ ]:
Data.tail(5)

,No.,Student Name,Project Title,Dataset Sheet,Rows,Columns,Status,Unnamed: 7,Data Quality Note
19,20,Nimca Abdiraxman Wehliye,Marketing Campaign Data Analysis,20_Marketing,300,7,Ready,NaN,NaN
20,21,Omar Abdullahi Mohamed,Bank Customer Data Analysis Using Excel,21_Bank,300,7,Ready,NaN,NaN
21,22,Ramla Abdi Osmaan,Insurance Customer Data Analysis Using Excel,22_Insurance,300,7,Ready,NaN,NaN
22,23,Shukri idiris mahamed,Crime Statistics Data Analysis,23_Crime,300,7,Ready,NaN,NaN
23,24,Sucdi Yasin Husein,Job Recruitment and Applicant Data Analysis,24_Recruitment,300,7,Ready,NaN,NaN

dispaly all colmns names

In [ ]:
Data.columns

Index(['No.', 'Student Name', 'Project Title', 'Dataset Sheet', 'Rows',
       'Columns', 'Status', 'Unnamed: 7', 'Data Quality Note'],
      dtype='object')

display the datatype using property(datatype)

In [ ]:
Data.dtypes

No.                    int64
Student Name          object
Project Title         object
Dataset Sheet         object
Rows                   int64
Columns                int64
Status                object
Unnamed: 7           float64
Data Quality Note     object
dtype: object

summary of datafarme

In [ ]:
Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   No.                24 non-null     int64
 1   Student Name       24 non-null     object
 2   Project Title      24 non-null     object
 3   Dataset Sheet      23 non-null     object
 4   Rows               24 non-null     int64
 5   Columns            24 non-null     int64
 6   Status             24 non-null     object
 7   Unnamed: 7         0 non-null      float64
 8   Data Quality Note  1 non-null      object
dtypes: float64(1), int64(3), object(5)
memory usage: 1.8+ KB

display the describe

In [ ]:
Data.describe()

             No.        Rows    Columns  Unnamed: 7
count  24.000000   24.000000  24.000000         0.0
mean   12.500000  287.500000   6.708333         NaN
std     7.071068   61.237244   1.428869         NaN
min     1.000000    0.000000   0.000000         NaN
25%     6.750000  300.000000   7.000000         NaN
50%    12.500000  300.000000   7.000000         NaN
75%    18.250000  300.000000   7.000000         NaN
max    24.000000  300.000000   7.000000         NaN