Renaming columns

In [1]:
import pandas as pd
data=pd.read_excel("/content/drive/MyDrive/Colab Notebooks/airline project.xlsx")

Renaming Columns

In [2]:
data=data.rename(columns={"BKGID":"Booking_ID"})

Reblace with value

In [3]:
data['Travel_Class'].value_counts()

Travel_Class
Economy     239
Business     43
business      2
ECONOMY       1
Name: count, dtype: int64

In [5]:
data["Travel_Class"]=data["Travel_Class"].replace("ECNMY","ECONOMY")

In [8]:
data.head()

,Booking_ID,Flight_Date,Route,Passenger_Type,Travel_Class,Ticket_Price,Booking_Status
0,ABK00122,2025-01-04,MGQ-HGA,Adult,Economy,NaN,Confirmed
1,ABK00143,2025-04-14,MGQ-ADD,Adult,Economy,235.06,Completed
2,ABK00187,2025-06-28,MGQ-ADD,Child,Economy,266.49,Completed
3,ABK00033,2026-03-14,MGQ-NBO,Adult,Economy,235.81,NaN
4,ABK00016,2025-10-19,MGQ-ADD,Child,Economy,NaN,Completed

Removing Unnecessary Columns

In [ ]:
data.drop(
columns=["Booking_ID"]
)

changing data types

In [10]:
data.dtypes

Booking_ID                object
Flight_Date       datetime64[ns]
Route                     object
Passenger_Type            object
Travel_Class              object
Ticket_Price              object
Booking_Status            object
dtype: object

In [11]:
data['Ticket_Price']=pd.to_numeric(data["Ticket_Price"],errors="coerce")

In [12]:
data['Flight_Date'] = pd.to_datetime(data['Flight_Date'], errors='coerce')

str.strip()

In [20]:
data["Route"].value_counts()

Route
MGQ-NBO    87
MGQ-ADD    60
MGQ-HGA    56
MGQ-BSA    45
MGQ-KMU    35
UNKNOWN     1
Name: count, dtype: int64

In [13]:
data["Route"] = data["Route"].str.strip()

 str.lower()

In [15]:
data["Travel_Class"] = data["Travel_Class"].str.lower()

In [26]:
data["Travel_Class"].value_counts()

Travel_Class
Economy     239
Business     45
ECONOMY       1
Name: count, dtype: int64

In [25]:
data[data["Passenger_Type"].str.lower() == "ECONOMY"]

Empty DataFrame
Columns: [Booking_ID, Flight_Date, Route, Passenger_Type, Travel_Class, Ticket_Price, Booking_Status]
Index: []

str.upper()

In [27]:
data["Route"] = data["Route"].str.upper()

str.title()

In [ ]:
data["Booking_Status"] = data["Booking_Status"].str.title()

In [28]:
data["Booking_Status"].value_counts()

Booking_Status
Completed    165
Confirmed     82
Cancelled     28
Unknown        3
cancelled      2
completed      2
-              1
Name: count, dtype: int64